### ISSUE TITLE
Behave yourself

### ISSUE THREAD

**Issue by ZWolken** [casioclasspad/casioclasspad.github.io#4]
Please behave yourself.
Read [GitHub Terms of Service](https://docs.github.com/site-policy/github-terms/github-terms-of-service).
I don't want to say more than that.

**Comment by takinekotfs** [comment]
If you have nothing then move to [Discussion](https://github.com/casioclasspad/casioclasspad.github.io/discussions).

The issue page is only used for reporting bugs, or suggest new features for this repo.

**Comment by casioclasspad** [comment]
Lock the conversation because this is not an issue, nor feature request.
